VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "vbCompilerDirectiveEndIf"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Implements vbStmt

Private Sub vbStmt_stmtParse(ByVal tokens As Collection)
tokens.Remove 1 ' End
If getKeyword(tokens.Item(1)) <> KW_IF Then Err.Raise 1 ' Expecting If keyword
tokens.Remove 1 ' If
CompilerIfStack.Remove CompilerIfStack.count
End Sub
