VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "vbOprUnary"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function oprGetResultTypeBinary(ByVal o As TliVarType) As TliVarType

End Function

Public Sub oprLetResultTypeBinary(ByVal o As TliVarType, ByVal vt As TliVarType)

End Sub

Public Function oprCoerceOperandUnary(ByVal cOutputStack As Collection) As TliVarType

End Function

Public Function oprOperateBinary(ByVal o As Variant) As Variant

End Function
