VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "vbOprBinary"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function oprGetResultTypeBinary(ByVal l As TliVarType, ByVal r As TliVarType) As TliVarType

End Function

Public Sub oprLetResultTypeBinary(ByVal l As TliVarType, ByVal r As TliVarType, ByVal vt As TliVarType)

End Sub

Public Function oprCoerceOperandsBinary(ByVal cOutputStack As Collection) As TliVarType

End Function

Public Function oprOperateBinary(ByVal l As Variant, ByVal r As Variant) As Variant

End Function
