VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "vbtForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public formVB_Name As String
Public formVB_GlobalNameSpace As Boolean
Public formVB_Creatable As Boolean
Public formVB_PredeclaredId As Boolean
Public formVB_Exposed As Boolean

#If 0 Then
Version 5#
Begin VB.Form Form1
   Caption = "Form1"
   ClientHeight = 3195
   ClientLeft = 60
   ClientTop = 345
   ClientWidth = 4680
   LinkTopic = "Form1"
   ScaleHeight = 3195
   ScaleWidth = 4680
   StartUpPosition = 3    'Windows Default
End
Option Explicit
#End If
